# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Asit Khanda Blog
email: asitkhanda@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Photographer, PC Builder, Gamer & Gadget Nerd. This is my personal blog where I write about stuff I feel digging like.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: edgeinfinite
facebook_username: staticpixel
github_username:  writecodeaf

# Build settings
markdown: kramdown
remote_theme: chesterhow/tale
#theme: minimal

permalink:    /:year-:month-:day/:title
paginate:     5


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
